CONTIKI = ../..
CONTIKI_PROJECT = stomp-client
APPS = stomp

WITH_UIP6 = 1
UIP_CONF_IPV6 = 1
TARGET = avr-zigduino
AVRDUDE_PORT = /dev/ttyUSB0

all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
