ifndef CONTIKI
CONTIKI = ../..
endif

CONTIKI_PROJECT = hello-uip

# TARGET = avr-zigduino
# TARGET = native
TARGET = minimal-net
# APPS = stomp 

#WITH_UIP6 = 1
#UIP_CONF_IPV6 = 1

all: $(CONTIKI_PROJECT)

include $(CONTIKI)/Makefile.include
